"""
report_response.py

API response schema for biomedical research report generation.

This module defines the response model returned after generating a
scientific research report.

Response schemas belong to the Presentation layer and are responsible for
serializing domain entities into JSON objects suitable for HTTP
transmission.

The ReportResponse intentionally contains no business logic. It provides
a stable contract between the BioResearch AI backend and client
applications while remaining independent of the internal domain model.

Architecture
------------

        ResearchReport
              │
              ▼
      ReportResponse
              │
              ▼
        HTTP Response
              │
              ▼
      Web UI / API Client

Future versions may include additional information such as:

- evidence quality assessments;
- agent execution traces;
- generated figures;
- experimental recommendations;
- report version history;
- export links (PDF, DOCX, Markdown);
- reviewer comments.

Author
------
Guillermo Ramajo Fernández
"""

from __future__ import annotations

from datetime import UTC
from datetime import datetime

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field

from app.domain.entities.research_report import ResearchReport


class ReportResponse(BaseModel):
    """
    Serialized representation of a biomedical research report.

    A ReportResponse contains the synthesized scientific evidence,
    supporting references and metadata describing
    the generated report.

    Attributes
    ----------
    workspace_id : str
        Identifier of the originating Research Workspace.

    summary : str
        Executive summary of the available scientific evidence.

    citations : list[str]
        Human-readable citations supporting the report.

    limitations : list[str]
        Known limitations of the available evidence.

    future_work : list[str]
        Suggested future research directions.

    generated_at : datetime
        UTC timestamp indicating when the report was generated.
    """

    model_config = ConfigDict(from_attributes=True)

    workspace_id: str = Field(
        description="Identifier of the originating Research Workspace."
    )

    summary: str = Field(
        description="Executive summary of the generated research report."
    )

    citations: list[str] = Field(
        default_factory=list,
        description="Scientific references supporting the report."
    )

    limitations: list[str] = Field(
        default_factory=list,
        description="Known limitations identified during evidence synthesis."
    )

    future_work: list[str] = Field(
        default_factory=list,
        description="Suggested future research directions."
    )

    generated_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="UTC timestamp indicating when the report was generated."
    )

    @property
    def has_limitations(self) -> bool:
        """
        Determine whether the report documents known limitations.

        Returns
        -------
        bool
            True if one or more limitations are available.
        """
        return bool(self.limitations)

    @property
    def has_future_work(self) -> bool:
        """
        Determine whether future research directions are available.

        Returns
        -------
        bool
            True if follow-up recommendations exist.
        """
        return bool(self.future_work)

    @property
    def citation_count(self) -> int:
        """
        Return the number of supporting citations.

        Returns
        -------
        int
            Number of citations included in the report.
        """
        return len(self.citations)

    @classmethod
    def from_domain(
        cls,
        workspace_id: str,
        report: ResearchReport,
    ) -> "ReportResponse":
        """
        Build a ReportResponse from a domain ResearchReport.

        Parameters
        ----------
        workspace_id : str
            Identifier of the originating Research Workspace.

        report : ResearchReport
            Domain report generated by the application layer.

        Returns
        -------
        ReportResponse
            Serialized API response.
        """

        return cls(
            workspace_id=workspace_id,
            summary=report.summary.text,
            citations=[
                str(citation)
                for citation in report.citations
            ],
            limitations=report.limitations,
            future_work=report.future_work,
        )