"""
citation_style.py

Enumeration of supported citation styles.

Purpose
-------
Scientific reports generated by BioResearch AI may be exported using
different citation standards depending on the target audience or
publication requirements.

This enumeration centralizes the supported citation formats.

Author
------
Guillermo Ramajo Fernández
"""

from enum import StrEnum


class CitationStyleEnum(StrEnum):
    """
    Supported scientific citation styles.
    """

    APA = "APA"
    MLA = "MLA"
    IEEE = "IEEE"
    VANCOUVER = "Vancouver"