"""
report_format.py

Enumeration of supported report formats.

Purpose
-------
Research reports generated by BioResearch AI may be exported in multiple
formats depending on downstream consumers.

This enumeration centralizes the supported output formats.

Author
------
Guillermo Ramajo Fernández
"""

from enum import StrEnum


class ReportFormatEnum(StrEnum):
    """
    Supported report output formats.
    """

    MARKDOWN = "markdown"
    HTML = "html"
    PDF = "pdf"
    JSON = "json"