"""
research_report.py

Domain entity representing the final scientific report generated during
a biomedical research session.

A ResearchReport is a structured synthesis of the scientific evidence
retrieved and analyzed throughout a ResearchSession. It captures the
principal findings, supporting references, identified limitations, and
recommended future directions.

Unlike a Summary, which represents an intermediate synthesis of the
retrieved literature, a ResearchReport is intended to be the final
deliverable presented to the researcher.

The report is intentionally independent of any presentation format.
Rendering the report as Markdown, HTML, PDF, DOCX, JSON, or a web page
is the responsibility of the presentation layer.

Likewise, this entity contains no infrastructure concerns. It does not
know how language models operate, where papers were retrieved from, or
how the report will ultimately be stored or transmitted.

Responsibilities
----------------
A ResearchReport is responsible for representing:

- Executive scientific conclusions
- Supporting evidence
- Known limitations
- Suggested future work
- Confidence assessment
- Report metadata

It is **not** responsible for:

- Literature retrieval
- Evidence synthesis
- Prompt engineering
- LLM interactions
- Rendering or formatting
- Database persistence

Author
------
Guillermo Ramajo Fernández
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.domain.entities.citation import Citation
from app.domain.entities.summary import Summary


@dataclass(slots=True)
class ResearchReport:
    """
    Represents the final scientific report produced during a biomedical
    research session.

    The report consolidates the synthesized evidence into a structured
    scientific document suitable for researchers, clinicians, and
    decision-makers.

    It serves as the principal output generated by BioResearch AI after
    literature retrieval and evidence synthesis have been completed.

    Attributes
    ----------
    summary : Summary
        Synthesized evidence generated from the retrieved literature.

    citations : list[Citation]
        Scientific references supporting the report.

    limitations : list[str]
        Known limitations, uncertainties, assumptions, or areas where the
        available evidence is insufficient.

    future_work : list[str]
        Suggested follow-up experiments, analyses, or research directions.

    confidence : float | None
        Overall confidence assigned to the report.

        Expected range
        --------------
        0.0
            Very low confidence.

        1.0
            Very high confidence.

    metadata : dict[str, str]
        Optional metadata describing report generation, such as:

        - LLM provider
        - Model version
        - Generation timestamp
        - Search strategy
        - Workflow version

    Notes
    -----
    This entity belongs to the Domain layer and therefore remains
    independent of any user interface or storage mechanism.

    The same report may later be rendered as:

    - Web page
    - REST API response
    - Markdown
    - PDF
    - DOCX
    - JSON
    - Jupyter Notebook

    without requiring modifications to the domain model.
    """

    summary: Summary

    citations: list[Citation] = field(default_factory=list)

    limitations: list[str] = field(default_factory=list)

    future_work: list[str] = field(default_factory=list)

    confidence: float | None = None

    metadata: dict[str, str] = field(default_factory=dict)

    @property
    def has_citations(self) -> bool:
        """
        Determine whether the report contains supporting references.

        Returns
        -------
        bool
            True if at least one citation is present.
        """
        return bool(self.citations)

    @property
    def has_limitations(self) -> bool:
        """
        Determine whether limitations have been documented.

        Returns
        -------
        bool
            True if one or more limitations are available.
        """
        return bool(self.limitations)

    @property
    def has_future_work(self) -> bool:
        """
        Determine whether future research directions are available.

        Returns
        -------
        bool
            True if follow-up recommendations exist.
        """
        return bool(self.future_work)

    def add_citation(self, citation: Citation) -> None:
        """
        Add a supporting scientific citation.

        Parameters
        ----------
        citation : Citation
            Scientific reference supporting the report.
        """
        self.citations.append(citation)

    def add_limitation(self, limitation: str) -> None:
        """
        Add a documented limitation.

        Parameters
        ----------
        limitation : str
            Description of a known limitation or uncertainty.
        """
        if limitation.strip():
            self.limitations.append(limitation)

    def add_future_work(self, recommendation: str) -> None:
        """
        Add a recommended future research direction.

        Parameters
        ----------
        recommendation : str
            Suggested follow-up experiment, analysis, or investigation.
        """
        if recommendation.strip():
            self.future_work.append(recommendation)

    def set_confidence(self, confidence: float) -> None:
        """
        Assign an overall confidence score to the report.

        Parameters
        ----------
        confidence : float
            Confidence score between 0.0 and 1.0.

        Raises
        ------
        ValueError
            If the confidence score falls outside the valid range.
        """
        if not 0.0 <= confidence <= 1.0:
            raise ValueError(
                "Confidence must be between 0.0 and 1.0."
            )

        self.confidence = confidence