"""
summary.py

Domain entity representing an AI-generated summary of a collection of
scientific publications.

A Summary is one of the core domain objects in BioResearch AI. It captures
the synthesized knowledge produced by a language model after analyzing a
set of biomedical papers in response to a research question.

This entity intentionally contains no AI logic, prompting, or API calls.
Its responsibility is simply to represent the result of a summarization
process in a framework-independent way.

The actual summarization is performed by implementations of the
LLMProvider interface located in the infrastructure layer.

Author
------
Guillermo Ramajo Fernández
"""

from __future__ import annotations

from dataclasses import dataclass, field

from app.domain.entities.paper import Paper


@dataclass(slots=True, frozen=True)
class Summary:
    """
    Represents a synthesized summary generated from one or more papers.

    A Summary encapsulates the textual output generated by an AI model,
    together with metadata describing how reliable the answer is and
    which scientific publications contributed to it.

    This entity belongs to the Domain layer and therefore must remain
    independent of any specific AI framework or provider
    (e.g. OpenAI, Anthropic, Ollama, Gemini).

    Attributes
    ----------
    text : str
        The generated summary presented to the researcher.

    papers_used : list[Paper]
        Scientific publications used to generate the summary.

        This provides traceability and allows downstream components
        to generate citations or inspect the supporting evidence.
    """

    text: str

    papers_used: list[Paper] = field(default_factory=list)

    @property
    def paper_count(self) -> int:
        """
        Return the number of papers contributing to this summary.

        Returns
        -------
        int
            Number of supporting publications.
        """
        return len(self.papers_used)

    @property
    def has_supporting_evidence(self) -> bool:
        """
        Determine whether the summary is backed by at least one paper.

        Returns
        -------
        bool
            True if one or more papers contributed to the summary,
            otherwise False.
        """
        return self.paper_count > 0

    def __str__(self) -> str:
        """
        Return a concise human-readable representation.

        Returns
        -------
        str
            Short description of the summary.
        """
        return f"Summary(papers={self.paper_count})"