"""
summarize_literature.py

Application use case responsible for synthesizing scientific literature
into a concise evidence-based summary.

This module orchestrates the summarization workflow without depending on
any concrete Large Language Model provider. Instead, it interacts only
with abstractions defined in the Domain layer.

Workflow
--------
Research Question
        │
        ▼
Prompt Builder
        │
        ▼
Prompt
        │
        ▼
LLM Provider
        │
        ▼
LLM Response
        │
        ▼
Summary

Following Clean Architecture principles, this use case contains
application logic but delegates infrastructure-specific concerns
(API calls, authentication, retries, etc.) to the infrastructure layer.

Author
------
Guillermo Ramajo Fernández
"""

from __future__ import annotations

import logging

from app.domain.entities.paper import Paper
from app.domain.entities.research_question import ResearchQuestion
from app.domain.entities.summary import Summary
from app.domain.interfaces.llm_provider import LLMProvider
from app.domain.models.prompt import Prompt
from app.infrastructure.llm.citation_sanitizer import (
    sanitize_citation_markers,
)


logger = logging.getLogger(__name__)


class SummarizePapersUseCase:
    """
    Summarize a collection of scientific papers.

    This use case is responsible for coordinating the literature
    summarization workflow.

    It constructs a provider-independent Prompt describing the task,
    delegates text generation to the configured LLM provider, and
    converts the resulting response into the project's Summary domain
    entity.

    The class is intentionally unaware of:

    - OpenAI
    - Anthropic
    - Ollama
    - Gemini
    - Azure OpenAI

    Any provider implementing the ``LLMProvider`` interface can be used
    without modifying this class.
    """

    def __init__(
        self,
        llm_provider: LLMProvider,
    ) -> None:
        """
        Initialize the use case.

        Parameters
        ----------
        llm_provider
            Concrete implementation of the language model provider.
        """
        self._llm_provider = llm_provider

    def execute(
        self,
        question: ResearchQuestion,
        papers: list[Paper],
    ) -> Summary:
        """
        Generate an evidence-based summary for a scientific question.

        Parameters
        ----------
        question
            Scientific question provided by the user.

        papers
            Scientific publications retrieved from one or more
            literature databases.

        Returns
        -------
        Summary
            Structured summary generated by the language model.

        Raises
        ------
        ValueError
            If no papers are provided.
        """

        if not papers:
            raise ValueError(
                "Cannot summarize an empty collection of papers."
            )

        # Number each paper 1..N so the LLM can reference them by
        # ``[paper:N]`` markers in its synthesis. This is the
        # same numbering the report prompt uses, so the report
        # mapper can extract these markers from the summary text
        # and use them to build a reliable citation list -- no
        # string-matching on paraphrased titles required.
        #
        # We number from the ``papers`` list order, which is
        # already the order they were added to the workspace
        # (most relevant first). The LLM sees the indices and
        # preserves them in the summary text.
        context_lines: list[str] = []
        for index, paper in enumerate(papers, start=1):
            context_lines.append(
                f"[paper:{index}]\n"
                f"Title: {paper.title}\n"
                f"Abstract: {paper.abstract}"
            )
        context = "\n\n".join(context_lines)

        prompt = Prompt(
            system=(
                "You are an expert biomedical research assistant. "
                "Summarize the scientific evidence objectively, "
                "highlight consensus and disagreements when present, "
                "and avoid unsupported conclusions.\n\n"
                "Citation style -- Vancouver / ICMJE\n"
                "------------------------------------\n"
                "Use bracket-number in-text citations at the END of "
                "the sentence or clause being cited, placed BEFORE "
                "the period. Every factual claim must be backed by "
                "a citation; every citation must appear at the "
                "natural end of the cited material. Write coherent "
                "scientific paragraphs in which one citation (or a "
                "bracketed group of citations) closes the "
                "sentence. Do NOT prefix sentences with [paper:N]; "
                "do NOT emit one citation per line; do NOT break "
                "the paragraph after every citation.\n\n"
                "Marker format\n"
                "-------------\n"
                "Whenever you cite a paper, preserve its ``[paper:N]`` "
                "marker VERBATIM in the text -- this is how "
                "downstream tooling extracts citations. The marker "
                "must appear inline, not on its own line. Multiple "
                "citations for a single claim appear as a bracketed "
                "group at one position, not scattered across the "
                "paragraph: ``...elevated in carriers [paper:5, "
                "paper:12]``.\n\n"
                "What good output looks like\n"
                "-----------------------------\n"
                "GOOD (one paragraph, citations at sentence ends):\n"
                "  Plasma p-tau217 is a sensitive and specific "
                "screening test for AD [paper:19]. BBMs are poised "
                "to expand access, but only 6% of UK memory services "
                "currently meet AD biomarker access guidelines "
                "[paper:10]. Successive diagnostic criteria have "
                "increasingly narrowed AD definition around amyloid "
                "and tau biomarkers [paper:15].\n\n"
                "BAD (one citation per line, prefix style):\n"
                "  [paper:19] argues that phosphorylated tau217 ...\n"
                "  [paper:10] highlights that BBMs are poised ...\n"
                "  [paper:15] observes that successive diagnostic ...\n\n"
                "Write like GOOD. Never like BAD.\n\n"
                "Bibliography size constraint\n"
                "----------------------------\n"
                "The bibliography for this summary contains exactly "
                f"{len(papers)} entries -- numbered ``[paper:1]`` "
                f"through ``[paper:{len(papers)}]``. Every citation marker "
                "you emit MUST be in that range.\n"
                "DO NOT emit ``[paper:N]`` for any N > "
                f"{len(papers)} -- there is no corresponding bibliography "
                "entry, and downstream tools will silently drop the marker, "
                "leaving the user's reading experience with a missing "
                "citation. If you find yourself wanting to cite a paper "
                "that isn't in the bibliography, do not cite it."
            ),
            user=question.question,
            context=context,
            temperature=0.2,
        )

        response = self._llm_provider.generate(prompt)

        # Sanitise the LLM output at the ingest boundary so
        # hallucinated ``[paper:N]`` markers (where N exceeds
        # the bibliography size) never reach persistent
        # storage. The prompt already warns the LLM about
        # the bibliography size, but in practice models
        # still hallucinate indices past the bound. We
        # silently drop them here and log a warning so
        # developers see the data-quality signal.
        # Defence-in-depth: the frontend linkifier also
        # drops out-of-range markers at render time, but
        # sanitising at ingest keeps the stored text clean
        # and avoids needing to re-strip on every read.
        sanitized_text = sanitize_citation_markers(
            response.content,
            len(papers),
        )

        # Fallback: inject an H1 title if the synthesis LLM
        # omitted one. Both downstream consumers (the PDF
        # generator and the React UI) extract the report
        # title from the first ``# `` line of
        # ``summary.body``. When the LLM skips the H1 the
        # user sees the generic ``"Biomedical Research
        # Report"`` label everywhere -- the fallback derives
        # a title from the first sentence and prepends it
        # so the consumers pick it up automatically.
        #
        # The fallback is idempotent (no-op when the body
        # already starts with ``# ``) so the LLM's choice
        # of title wins when present. See
        # ``app/infrastructure/llm/title_fallback.py`` for
        # the derivation algorithm and rationale.
        from app.infrastructure.llm.title_fallback import (
            inject_h1_fallback,
        )
        body_with_title = inject_h1_fallback(sanitized_text)
        if body_with_title != sanitized_text:
            logger.info(
                "summarize_papers: injected H1 fallback title "
                "because the synthesis LLM omitted one. "
                "title=%r",
                body_with_title.split("\n", 1)[0],
            )

        return Summary(
            body=body_with_title,
            papers_used=papers,
        )