"""
summarize_literature.py

Application use case responsible for synthesizing scientific literature
into a concise evidence-based summary.

This module orchestrates the summarization workflow without depending on
any concrete Large Language Model provider. Instead, it interacts only
with abstractions defined in the Domain layer.

Workflow
--------
Research Question
        │
        ▼
Prompt Builder
        │
        ▼
Prompt
        │
        ▼
LLM Provider
        │
        ▼
LLM Response
        │
        ▼
Summary

Following Clean Architecture principles, this use case contains
application logic but delegates infrastructure-specific concerns
(API calls, authentication, retries, etc.) to the infrastructure layer.

Author
------
Guillermo Ramajo Fernández
"""

from __future__ import annotations

from app.domain.entities.paper import Paper
from app.domain.entities.research_question import ResearchQuestion
from app.domain.entities.summary import Summary
from app.domain.interfaces.llm_provider import LLMProvider
from app.domain.models.prompt import Prompt


class SummarizePapersUseCase:
    """
    Summarize a collection of scientific papers.

    This use case is responsible for coordinating the literature
    summarization workflow.

    It constructs a provider-independent Prompt describing the task,
    delegates text generation to the configured LLM provider, and
    converts the resulting response into the project's Summary domain
    entity.

    The class is intentionally unaware of:

    - OpenAI
    - Anthropic
    - Ollama
    - Gemini
    - Azure OpenAI

    Any provider implementing the ``LLMProvider`` interface can be used
    without modifying this class.
    """

    def __init__(
        self,
        llm_provider: LLMProvider,
    ) -> None:
        """
        Initialize the use case.

        Parameters
        ----------
        llm_provider
            Concrete implementation of the language model provider.
        """
        self._llm_provider = llm_provider

    def execute(
        self,
        question: ResearchQuestion,
        papers: list[Paper],
    ) -> Summary:
        """
        Generate an evidence-based summary for a scientific question.

        Parameters
        ----------
        question
            Scientific question provided by the user.

        papers
            Scientific publications retrieved from one or more
            literature databases.

        Returns
        -------
        Summary
            Structured summary generated by the language model.

        Raises
        ------
        ValueError
            If no papers are provided.
        """

        if not papers:
            raise ValueError(
                "Cannot summarize an empty collection of papers."
            )

        context = "\n\n".join(
            f"Title: {paper.title}\n"
            f"Abstract: {paper.abstract}"
            for paper in papers
        )

        prompt = Prompt(
            system=(
                "You are an expert biomedical research assistant. "
                "Summarize the scientific evidence objectively, "
                "highlight consensus and disagreements when present, "
                "and avoid unsupported conclusions."
            ),
            user=question.question,
            context=context,
            temperature=0.2,
        )

        response = self._llm_provider.generate(prompt)

        return Summary(
            text=response.content,
            confidence=None,
            papers_used=papers,
        )