"""
test_pdf_structured_extractor.py

Unit tests for :mod:`app.infrastructure.pubmed.pdf_structured_extractor`.

The structured extractor parses PDF text into a ``Paper`` entity
when external lookup (CrossRef / PubMed) fails. These tests pin
the heuristics: title detection, author splitting, year
extraction, abstract boundaries, keyword line.

We feed the extractor a real PDF (the bioRxiv preprint the user
attached) and several synthetic PDFs generated by ``_pdf_with_text``
so the tests run without network access.
"""

from __future__ import annotations

import io
from pathlib import Path

import pytest


# ---------------------------------------------------------------------
# Synthetic PDF builder — minimal hand-rolled PDF 1.4 with one page.
# We avoid pypdf's high-level PageObject because injecting arbitrary
# text through it is fiddly across pypdf versions.
# ---------------------------------------------------------------------


def _pdf_with_text(text: str) -> bytes:
    """Return a minimal PDF whose first page contains ``text``."""
    text = text.replace("(", r"\(").replace(")", r"\)")
    stream = b"BT /F1 12 Tf 50 700 Td (" + text.encode() + b") Tj ET"
    n = len(stream)
    return (
        b"%PDF-1.4\n"
        b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
        b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"
        b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
        b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n"
        b"4 0 obj\n<< /Length " + str(n).encode() + b" >>\nstream\n"
        + stream
        + b"\nendstream\nendobj\n"
        b"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n"
        b"xref\n0 6\n0000000000 65535 f \n"
        b"0000000009 00000 n \n0000000058 00000 n \n"
        b"0000000115 00000 n \n0000000218 00000 n \n"
        b"0000000310 00000 n \ntrailer\n<< /Size 6 /Root 1 0 R >>\n"
        b"startxref\n374\n%%EOF\n"
    )


# ---------------------------------------------------------------------
# Real PDF — the bioRxiv preprint the user attached.
# ---------------------------------------------------------------------


@pytest.fixture(scope="module")
def biorxiv_pdf_bytes() -> bytes:
    """The bioRxiv preprint the user uploaded."""
    attachment = Path(
        "/home/grf/.hermes/webui/attachments/ee846461fd2e/"
        "2026.03.31.715296v1.full.pdf"
    )
    if not attachment.exists():
        pytest.skip(
            "bioRxiv PDF attachment not present — only run when the "
            "user-attached PDF is on disk."
        )
    return attachment.read_bytes()


def test_extract_title_and_authors_from_biorxiv(biorxiv_pdf_bytes):
    """The bioRxiv preprint's first page has a recognisable
    title + 10 authors + 2026 year + 'Keywords:' line +
    'Abstract' header. The structured extractor must surface
    them all.
    """
    from app.infrastructure.pubmed.pdf_structured_extractor import (
        extract_paper_from_pdf,
    )

    result = extract_paper_from_pdf(io.BytesIO(biorxiv_pdf_bytes))
    assert result is not None

    paper = result.paper
    assert "Alzheimer" in paper.title
    assert "Phenotypes" in paper.title or "Brain" in paper.title
    assert paper.year == 2026
    assert paper.authors[0].last_name == "Travi"
    assert paper.authors[-1].last_name == "Polosecki"
    assert len(paper.authors) >= 5
    assert paper.abstract.startswith(
        "A widespread view of neurodegenerative"
    )
    assert any(
        "deep learning" in kw.lower() for kw in paper.keywords
    )


def test_extract_doi_from_biorxiv(biorxiv_pdf_bytes):
    """The bioRxiv footer renders the DOI without a space
    before the literal ``doi:`` — ``...10.64898/2026.03.31.715296doi: bioRxiv``.
    The structured extractor must peel off the trailing
    ``doi:`` so the DOI is clean.
    """
    from app.infrastructure.pubmed.pdf_structured_extractor import (
        extract_paper_from_pdf,
    )

    result = extract_paper_from_pdf(io.BytesIO(biorxiv_pdf_bytes))
    assert result is not None
    paper = result.paper
    assert paper.doi == "10.64898/2026.03.31.715296"
    assert paper.url == "https://doi.org/10.64898/2026.03.31.715296"


# ---------------------------------------------------------------------
# Synthetic PDFs — pin the heuristics.
# ---------------------------------------------------------------------


def test_extract_handles_minimal_pdf():
    """A PDF with only a title should still yield a Paper —
    the other fields are None / empty."""
    from app.infrastructure.pubmed.pdf_structured_extractor import (
        extract_paper_from_pdf,
    )

    text = "A title about something interesting."
    pdf = _pdf_with_text(text)
    result = extract_paper_from_pdf(io.BytesIO(pdf))

    assert result is not None
    paper = result.paper
    assert "A title about something interesting" in paper.title
    assert paper.authors == []
    assert paper.abstract == ""
    assert paper.doi is None
    assert paper.year is None


def test_extract_raises_on_unreadable_pdf():
    """A file that can't be parsed as a PDF raises RuntimeError
    so the route can surface a 422."""
    from app.infrastructure.pubmed.pdf_structured_extractor import (
        extract_paper_from_pdf,
    )

    bad = b"this is not a pdf at all"
    with pytest.raises(RuntimeError):
        extract_paper_from_pdf(io.BytesIO(bad))


def test_extract_abstract_boundary():
    """The abstract ends at the next section break
    (``1 Introduction``). The text after that break is NOT
    included in the abstract."""
    from app.infrastructure.pubmed.pdf_structured_extractor import (
        extract_paper_from_pdf,
    )

    text = (
        "The Title Line\n"
        "Some Author\n"
        "Department of X\n"
        "Abstract\n"
        "This is the abstract. It goes on.\n"
        "1 Introduction\n"
        "This is the introduction. Not part of the abstract.\n"
    )
    pdf = _pdf_with_text(text)
    result = extract_paper_from_pdf(io.BytesIO(pdf))

    assert result is not None
    paper = result.paper
    assert "This is the abstract" in paper.abstract
    assert "introduction" not in paper.abstract.lower()


def test_extract_keywords_comma_split():
    """Keywords after the literal ``Keywords:`` line are split
    on commas and trimmed."""
    from app.infrastructure.pubmed.pdf_structured_extractor import (
        extract_paper_from_pdf,
    )

    text = (
        "Title of paper\n"
        "Author Name\n"
        "Department of X\n"
        "Keywords: Alzheimer's, deep learning, aging, brain\n"
        "Abstract\n"
        "Lorem ipsum.\n"
    )
    pdf = _pdf_with_text(text)
    result = extract_paper_from_pdf(io.BytesIO(pdf))

    assert result is not None
    paper = result.paper
    assert paper.keywords == [
        "Alzheimer's",
        "deep learning",
        "aging",
        "brain",
    ]


def test_extract_year_from_biorxiv_boilerplate():
    """bioRxiv footer ``this version posted April 2, 2026``
    yields 2026."""
    from app.infrastructure.pubmed.pdf_structured_extractor import (
        extract_paper_from_pdf,
    )

    text = (
        "The Paper Title\n"
        "A. Author\n"
        "Department of Y\n"
        "Abstract\n"
        "Lorem ipsum.\n"
        "bioRxiv preprint doi: https://doi.org/10.64898/2026.03.31.715296doi: "
        "this version posted April 2, 2026.\n"
    )
    pdf = _pdf_with_text(text)
    result = extract_paper_from_pdf(io.BytesIO(pdf))

    assert result is not None
    assert result.paper.year == 2026